### ISSUE TITLE
Ex62.1.jl 

### ISSUE THREAD

**Issue by OVGULIU** [PtFEM/PtFEM.jl#9]
In Ex62.1.jl 

I have found an **### error** message 

**ERROR: LoadError: error compiling _plot!: error compiling _display: could not load library "libGR.dll"
The specified module could not be found.**

**Comment by goedman** [comment]
Hi, 

Usually this indicates that the GR library has not been built. Can you try, in the REPL:
```
Pkg.build("GR")
```

Rob

**Comment by OVGULIU** [comment]
Thanks! It is solved!
